-- GENERATED by tools/mapdata.py from tools/instances.json -- do not edit by hand.
-- wow_classic_beta: 1.60.1.70205; wow_anniversary: 2.5.6.69795; names: wow 12.1.0.69933
--
-- Each alt is a candidate art set; Catalog uses the first whose art exists in
-- the running client. Floor 0 is a single page (<path><tile>), floors 1+ are
-- <path><floor>_<tile>. dims = cols, rows, tileW, tileH, contentW, contentH
-- when they differ from the classic 4, 3, 256, 256, 1002, 668.

local ADDON, ns = ...

ns.InstanceData = {
	{
		key = "moltencore", name = "Molten Core", kind = "raid", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\moltencore\\moltencore", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "onyxiaslair", name = "Onyxia's Lair", kind = "raid", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\onyxiaslair\\onyxiaslair", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "blackwinglair", name = "Blackwing Lair", kind = "raid", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\blackwinglair\\blackwinglair", floors = {
				{ 1, "Dragonmaw Garrison" },
				{ 2, "Halls of Strife" },
				{ 3, "Crimson Laboratories" },
				{ 4, "Nefarian's Lair" },
			} },
		},
	},
	{
		key = "zulgurub", name = "Zul'Gurub", kind = "raid", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\zulgurub\\zulgurub", floors = {
				{ 0, "" },
			} },
		},
	},
	{
		key = "ruinsofahnqiraj", name = "Ruins of Ahn'Qiraj", kind = "raid", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\ruinsofahnqiraj\\ruinsofahnqiraj", floors = {
				{ 0, "" },
			} },
		},
	},
	{
		key = "ahnqiraj", name = "Temple of Ahn'Qiraj", kind = "raid", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\ahnqiraj\\ahnqiraj", floors = {
				{ 1, "The Hive Undergrounds" },
				{ 2, "The Temple Gates" },
				{ 3, "Vault of C'Thun" },
			} },
		},
	},
	{
		key = "naxxramas", name = "Naxxramas", kind = "raid", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\naxxramas\\naxxramas", floors = {
				{ 1, "The Construct Quarter" },
				{ 2, "The Arachnid Quarter" },
				{ 3, "The Military Quarter" },
				{ 4, "The Plague Quarter" },
				{ 5, "The Lower Necropolis" },
				{ 6, "The Upper Necropolis" },
			} },
		},
	},
	{
		key = "ragefire", name = "Ragefire Chasm", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\ragefire\\ragefire", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "deadmines", name = "The Deadmines", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\thedeadmines\\thedeadmines", floors = {
				{ 1, "The Deadmines" },
				{ 2, "Ironclad Cove" },
			} },
		},
	},
	{
		key = "wailingcaverns", name = "Wailing Caverns", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\wailingcaverns\\wailingcaverns", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "shadowfangkeep", name = "Shadowfang Keep", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\shadowfangkeep\\shadowfangkeep", floors = {
				{ 1, "The Courtyard" },
				{ 2, "Dining Hall" },
				{ 3, "The Vacant Den" },
				{ 4, "Lower Observatory" },
				{ 5, "Upper Observatory" },
				{ 6, "Lord Godfrey's Chamber" },
				{ 7, "The Wall Walk" },
			} },
		},
	},
	{
		key = "blackfathomdeeps", name = "Blackfathom Deeps", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\blackfathomdeeps\\blackfathomdeeps", floors = {
				{ 1, "The Pool of Ask'Ar" },
				{ 2, "Moonshrine Sanctum" },
				{ 3, "The Forgotten Pool" },
			} },
		},
	},
	{
		key = "stockade", name = "The Stockade", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\thestockade\\thestockade", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "gnomeregan", name = "Gnomeregan", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\gnomeregan\\gnomeregan", floors = {
				{ 1, "The Hall of Gears" },
				{ 2, "The Dormitory" },
				{ 3, "Launch Bay" },
				{ 4, "Tinkers' Court" },
			} },
		},
	},
	{
		key = "razorfenkraul", name = "Razorfen Kraul", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\razorfenkraul\\razorfenkraul", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "scarletmonastery", name = "Scarlet Monastery", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\scarletmonastery\\scarletmonastery", floors = {
				{ 1, "Graveyard" },
				{ 2, "Library" },
				{ 3, "Armory" },
				{ 4, "Cathedral" },
			} },
		},
	},
	{
		key = "razorfendowns", name = "Razorfen Downs", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\razorfendowns\\razorfendowns", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "uldaman", name = "Uldaman", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\uldaman\\uldaman", floors = {
				{ 1, "Hall of the Keepers" },
				{ 2, "Khaz'Goroth's Seat" },
			} },
		},
	},
	{
		key = "zulfarrak", name = "Zul'Farrak", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\zulfarrak\\zulfarrak", floors = {
				{ 0, "" },
			} },
		},
	},
	{
		key = "maraudon", name = "Maraudon", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\maraudon\\maraudon", floors = {
				{ 1, "Caverns of Maraudon" },
				{ 2, "Zaetar's Grave" },
			} },
		},
	},
	{
		key = "sunkentemple", name = "Sunken Temple", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\thetempleofatalhakkar\\thetempleofatalhakkar", floors = {
				{ 1, "The Temple of Atal'Hakkar" },
			} },
		},
	},
	{
		key = "blackrockdepths", name = "Blackrock Depths", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\blackrockdepths\\blackrockdepths", floors = {
				{ 1, "Detention Block" },
				{ 2, "Shadowforge City" },
			} },
		},
	},
	{
		key = "blackrockspire", name = "Blackrock Spire", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\blackrockspire\\blackrockspire", floors = {
				{ 1, "Tazz'Alor" },
				{ 2, "Skitterweb Tunnels" },
				{ 3, "Hordemar City" },
				{ 4, "Hall of Blackhand" },
				{ 5, "Halycon's Lair" },
				{ 6, "Chamber of Battle" },
			} },
		},
	},
	{
		key = "diremaul", name = "Dire Maul", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\diremaul\\diremaul", floors = {
				{ 0, "Overview" },
				{ 1, "Gordok Commons" },
				{ 2, "Capital Gardens" },
				{ 3, "Court of the Highborne" },
				{ 4, "Prison of Immol'Thar" },
				{ 5, "Warpwood Quarter" },
				{ 6, "The Shrine of Eldretharr" },
			} },
		},
	},
	{
		key = "scholomance", name = "Scholomance", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\scholomanceold\\scholomanceold", floors = {
				{ 1, "The Reliquary" },
				{ 2, "Chamber of Summoning" },
				{ 3, "The Upper Study" },
				{ 4, "Headmaster's Study" },
			} },
			{ path = "Interface\\WorldMap\\scholomance\\scholomance", floors = {
				{ 1, "The Reliquary" },
				{ 2, "Chamber of Summoning" },
				{ 3, "The Upper Study" },
				{ 4, "Headmaster's Study" },
			} },
		},
	},
	{
		key = "stratholme", name = "Stratholme", kind = "dungeon", era = "vanilla",
		flavors = { vanilla = true, forever = true, tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\stratholme\\stratholme", floors = {
				{ 1, "Crusader's Square" },
				{ 2, "The Gauntlet" },
			} },
		},
	},
	{
		key = "karazhan", name = "Karazhan", kind = "raid", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\karazhan\\karazhan", floors = {
				{ 1, "Servant's Quarters" },
				{ 2, "Upper Livery Stables" },
				{ 3, "The Banquet Hall" },
				{ 4, "The Guest Chambers" },
				{ 5, "Opera Hall Balcony" },
				{ 6, "Master's Terrace" },
				{ 7, "Lower Broken Stair" },
				{ 8, "Upper Broken Stair" },
				{ 9, "The Menagerie" },
				{ 10, "Guardian's Library" },
				{ 11, "The Repository" },
				{ 12, "Upper Library" },
				{ 13, "The Celestial Watch" },
				{ 14, "Gamesman's Hall" },
				{ 15, "Medivh's Chambers" },
				{ 16, "The Power Station" },
				{ 17, "Netherspace" },
			} },
		},
	},
	{
		key = "gruulslair", name = "Gruul's Lair", kind = "raid", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\gruulslair\\gruulslair", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "magtheridonslair", name = "Magtheridon's Lair", kind = "raid", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\magtheridonslair\\magtheridonslair", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "serpentshrine", name = "Serpentshrine Cavern", kind = "raid", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\coilfangreservoir\\coilfangreservoir", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "tempestkeep", name = "Tempest Keep: The Eye", kind = "raid", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\tempestkeep\\tempestkeep", floors = {
				{ 1, "Tempest Keep" },
			} },
		},
	},
	{
		key = "hyjalsummit", name = "Hyjal Summit", kind = "raid", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\cotmounthyjal\\cotmounthyjal", floors = {
				{ 0, "" },
			} },
		},
	},
	{
		key = "blacktemple", name = "Black Temple", kind = "raid", era = "tbc",
		flavors = { tbc = true },
		verified = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\blacktemple\\blacktemple", floors = {
				{ 0, "Black Temple" },
				{ 1, "Karabor Sewers" },
				{ 2, "Sanctuary of Shadows" },
				{ 3, "Halls of Anguish" },
				{ 4, "Gorefiend's Vigil" },
				{ 5, "Den of Mortal Delights" },
				{ 6, "Chamber of Command" },
				{ 7, "Temple Summit" },
			} },
		},
	},
	{
		key = "zulaman", name = "Zul'Aman", kind = "raid", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\zulaman\\zulaman", floors = {
				{ 0, "" },
			} },
		},
	},
	{
		key = "sunwellplateau", name = "Sunwell Plateau", kind = "raid", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\sunwellplateau\\sunwellplateau", floors = {
				{ 0, "Sunwell Plateau" },
				{ 1, "Shrine of the Eclipse" },
			} },
		},
	},
	{
		key = "hellfireramparts", name = "Hellfire Ramparts", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\hellfireramparts\\hellfireramparts", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "bloodfurnace", name = "The Blood Furnace", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\thebloodfurnace\\thebloodfurnace", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "shatteredhalls", name = "The Shattered Halls", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\theshatteredhalls\\theshatteredhalls", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "slavepens", name = "The Slave Pens", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\theslavepens\\theslavepens", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "underbog", name = "The Underbog", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\theunderbog\\theunderbog", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "steamvault", name = "The Steamvault", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\thesteamvault\\thesteamvault", floors = {
				{ 1, "The Steamvault" },
				{ 2, "The Cooling Pools" },
			} },
		},
	},
	{
		key = "manatombs", name = "Mana-Tombs", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\manatombs\\manatombs", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "auchenaicrypts", name = "Auchenai Crypts", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\auchenaicrypts\\auchenaicrypts", floors = {
				{ 1, "Halls of the Hereafter" },
				{ 2, "Bridge of Souls" },
			} },
		},
	},
	{
		key = "sethekkhalls", name = "Sethekk Halls", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\sethekkhalls\\sethekkhalls", floors = {
				{ 1, "Veil Sethekk" },
				{ 2, "Halls of Mourning" },
			} },
		},
	},
	{
		key = "shadowlabyrinth", name = "Shadow Labyrinth", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\shadowlabyrinth\\shadowlabyrinth", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "oldhillsbrad", name = "Old Hillsbrad Foothills", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\cothillsbradfoothills\\cothillsbradfoothills", floors = {
				{ 0, "" },
			} },
		},
	},
	{
		key = "blackmorass", name = "The Black Morass", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\cottheblackmorass\\cottheblackmorass", floors = {
				{ 0, "" },
			} },
		},
	},
	{
		key = "mechanar", name = "The Mechanar", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\themechanar\\themechanar", floors = {
				{ 1, "The Mechanar" },
				{ 2, "Calculation Chamber" },
			} },
		},
	},
	{
		key = "botanica", name = "The Botanica", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\thebotanica\\thebotanica", floors = {
				{ 1, "" },
			} },
		},
	},
	{
		key = "arcatraz", name = "The Arcatraz", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\thearcatraz\\thearcatraz", floors = {
				{ 1, "Stasis Block: Trion" },
				{ 2, "Stasis Block: Maximus" },
				{ 3, "Containment Core" },
			} },
		},
	},
	{
		key = "magistersterrace", name = "Magisters' Terrace", kind = "dungeon", era = "tbc",
		flavors = { tbc = true },
		alts = {
			{ path = "Interface\\WorldMap\\magistersterrace\\magistersterrace", floors = {
				{ 1, "Grand Magister's Asylum" },
				{ 2, "Observation Grounds" },
			} },
		},
	},
	{
		key = "dalaran", name = "City of Dalaran", kind = "dungeon", era = "forever",
		flavors = { forever = true },
		alts = {
			{ path = "Interface\\WorldMap\\dalarancity\\dalarancity", floors = {
				{ 1, "Dalaran City" },
				{ 2, "The Underbelly" },
			} },
		},
	},
	{
		key = "ruinsoflordaeron", name = "Ruins of Lordaeron", kind = "dungeon", era = "forever",
		flavors = { forever = true },
		alts = {
			{ path = "Interface\\WorldMap\\ruinsoflordaeronscenario\\ruinsoflordaeronscenario", floors = {
				{ 0, "" },
			} },
		},
	},
	{
		key = "battleforgilneas", name = "Battle for Gilneas", kind = "bg", era = "forever",
		flavors = { forever = true },
		alts = {
			{ path = "Interface\\WorldMap\\gilneasbattleground2\\gilneasbattleground2", floors = {
				{ 0, "The Battle for Gilneas" },
			} },
		},
	},
}
